version: '3.5'
services:
    app:
        image: mcr.microsoft.com/devcontainers/php:1-8.2-bullseye
        container_name: app
        ports:
            - 8080:8080
        volumes:
            - .:/app:cached
    mysql:
        image: mysql:8.1.0
        container_name: mysql
        ports:
            - 3306:3306
        volumes:
            - .docker/mysql/data:/var/lib/mysql:cached
        environment:
            MYSQL_ROOT_PASSWORD: root
